export * from "./admins";
export * from "./staff";
export * from "./students";
export * from "./topStudents";
export * from "./notices";
export * from "./gallery";
export * from "./schoolInfo";
export * from "./casteStats";
export * from "./contact";
